services:
  - type: web
    name: medterm-bot
    runtime: node
    # يثبت ffmpeg و mupdf-tools تلقائياً عند كل deploy
    buildCommand: apt-get install -y ffmpeg mupdf-tools 2>/dev/null | true && npm install
    startCommand: node bot.js
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
