services:
  - type: web
    name: medterm-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
